platform :ios, '15.0'

target 'AijiaDirect' do
  use_frameworks!
  # 4.0.0a2 points to an archived/removed unstable download URL.
  # 3.4.0 is the latest stable binary still hosted by VideoLAN.
  pod 'MobileVLCKit', '3.4.0'
end
